auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: 田捷博客
url: https://violettianjie.github.io
feed: /atom.xml
author_info: <a href="https://violettianjie.github.io/">TianJie</a>
